---
title: "Distance sampling"
author: "Michelle DePrenger-Levin"
date: "2024-05-22"
output: html_document
---

```{r}

rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(tidyverse)
library(sf)
library(mapview)
library(leaflet)

# webshot::install_phantomjs()
```


Data from survey123      
https://researchdbg.maps.arcgis.com/home/item.html?id=56f4fbec07d94faeafe87b1e1503f459      
and     
https://researchdbg.maps.arcgis.com/home/item.html?id=db53858aae2f47a2bd8ac09366540b25       
```{r}
ds2024 <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScleroDistanceSampling/main/Data/plantData_1.csv")
nrow(ds2024) ## 1478 plants

dstrans <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScleroDistanceSampling/main/Data/transect_2.csv")
nrow(dstrans) # 35 line transects

## Transect.meter.mark and direction to group, and distance to group. x, y were GPS point 
ds_One <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScleroDistanceSampling/main/Data/distanceSampling_1.csv")

## Dataframe with date, recorded by, distance between transects, x, y
ds_zero <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScleroDistanceSampling/main/Data/Sclerocactus_glaucus_Distance_Sampling_0.csv")
nrow(ds_zero) # 25 transect starts?

ds_demographic <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScleroDistanceSampling/main/Data/Sclerocactus_glaucus_DemographicMonitoring_0.csv")
nrow(ds_demographic) # 79 transects with x,y


```


## Data checks
```{r}


## 4 records in site 1 --> are also Picnic, 1 record with NA for site --> should be OilPad
# the extra site numbers are due to advancing the transect instead of the record within a transect. 
siteIDs <- data.frame(SiteID = c('1','3','10','12','11'),
                      SiteName = c('Picnic', 'Picnic', 'Bridgeport', 'Fram', 'OilPad'))


## assuming we took data in WGS84 via the argument crs = 4326
## However, we were uncertain and stopped updating all the points. These points will also have spatial error ca. 1-10 meters
ds_One$siteName[is.na(ds_One$siteName)] <- 11
ds_One %>%
  mutate(siteName = as.factor(siteName)) %>%
  left_join(siteIDs, by = c("siteName" = "SiteID")) %>%
  filter(!is.na(x)) %>%
  filter(x != 0) %>%
mapview(  xcol = 'x', ycol = 'y', crs = 4269, grid = FALSE, 
          zcol = 'SiteName',
          label = ds_One$SiteName[ds_One$x != 0],
          labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))
## Labels appear when mouse hovers over


ds_One %>%
  mutate(siteName = as.factor(siteName)) %>%
  filter(!is.na(x)) %>%
  filter(x != 0) %>%
mapview(  xcol = 'x', ycol = 'y', crs = 4269, grid = FALSE, 
          zcol = 'siteName',
          label = ds_One$SiteName[ds_One$x != 0],
          labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))


## map transects from survey123 
ds_zero$site[is.na(ds_zero$site)] <- 11
ds_zero %>%
  rename(x_trans = x) %>%
  rename(y_trans = y) %>%
  left_join(ds_One, by = c("GlobalID" = "GlobalID")) %>%
  mutate(site = as.factor(site)) %>%
  left_join(siteIDs, by = c("site" = "SiteID")) %>%
  mapview(  xcol = 'x', ycol = 'y', crs = 4269, grid = FALSE,
            zcol = 'SiteName',
          label = ds_One$SiteName[ds_One$x != 0],
          labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))

## Demographic transects
ds_demographic %>%
  mutate(transect = as.factor(transect),
         site = as.factor(site)) %>%
  mapview(  xcol = 'x', ycol = 'y', crs = 4269, grid = FALSE,
            zcol = 'site',
          label = ds_demographic$transect,
          labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))
```


Save 'leaflet' as jpg or png   
```{r}
library(leaflet)
demoSites <- read.csv("https://raw.githubusercontent.com/DenverBotanicGardens/ScGl/master/datasets/_scgl_sites.csv")

# make rendered html self-contained
mapviewOptions(fgb = FALSE)

demo2plot <- ds_demographic %>%
  left_join(demoSites, by = c("site" = "ScGl_site_id"))
m <- demo2plot %>%
  mutate(transect = as.factor(transect),
         site = as.factor(site)) %>%
  mapview(  xcol = 'x', ycol = 'y', crs = 4269, grid = FALSE,
            zcol = 'SiteName')

  # ,
  #           label = ds_demographic$SiteName,
  #           labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))

mapshot(m, file = "C:/Users/deprengm/Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Sclerocactus-glaucus/Sclerocactus-glaucus_AnnualReports/DemographicSitesMap.png")

mapshot(m, file = "C:/Users/deprengm/Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Sclerocactus-glaucus/Sclerocactus-glaucus_AnnualReports/DemographicSitesMapv2.png",
         removeControl = c())
```







#############################################################################################################################
_____________________________________________________________________________________________________________________________


## Jonathan testing
```{r}
## it's not 2023, it's from 2024!
ds2023 <- read.csv("C:/Users/deprengm/Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Sclerocactus-glaucus/Sclerocactus-glaucus_Projects/2024_Sclerocactus-glaucus_distancesampling/JONATHAN TEST S123_2024_distanceSampling_ScGl/distanceSampling_1.csv")

head(ds2023)

trans2023 <- read.csv("C:/Users/deprengm/Denver Botanic Gardens/Conservation - General/AllProjectsBySpecies/Sclerocactus-glaucus/Sclerocactus-glaucus_Projects/2024_Sclerocactus-glaucus_distancesampling/JONATHAN TEST S123_2024_distanceSampling_ScGl/transect_2.csv")

head(trans2023)

scds <- ds2023 %>%
  left_join(trans2023, by = c("ParentGlobalID", "GlobalID"))
head(scds)
colSums(table(scds$GlobalID, scds$ParentGlobalID))
rowSums(table(scds$GlobalID, scds$ParentGlobalID))

## We did a second observation of transect 2 and called it 21. 
table(scds$siteName, scds$transectNumber_, scds$transectOrientation)

## the NS,EW has no data, a mistake to remove. 
scds %>%
  filter(Distance.To.Group > 6) 
## Typos, could drop, or could make best judgement to QC. 

## Typo needs help
scds %>%
  filter(Transect.Meter.Mark > 100)

scds %>%
  dplyr::select(x:X.3)



## Check and fix transect lengths when we didn't measure to the full tape length

```


Mark-recapture to get detection on the line
```{r}
## Site 11 is Oil Pad and is bad
## Sites 1 and 3 are the same
scds$siteName[scds$siteName == 3] <- 1
table(scds$siteName, scds$transectNumber_, scds$transectOrientation)

### Need all the increments of 10 (or spacing) to meet to have the 3x3 meter crossed design

## we want +/- from each transect, but need match up the appropriate crossing
crossed <- scds %>%
  filter(Distance.To.Group <= 3)


### Only Fram does the transect number match the meter mark (increment of 10meters)
cx <- lapply(split(scds, scds$siteName), function(x){
  
   
})


### Fram is 12
fram <- scds[scds$siteName == 12,]
fram <- fram %>%
  filter(!is.na(Transect.Meter.Mark))
## We left the demographic transects so transects ran North to South instead of S to N
fram$Transect.Meter.Mark[fram$transectOrientation == "NS"] <-
  100-fram$Transect.Meter.Mark[fram$transectOrientation == "NS"]

# fram %>%
#   filter(transectOrientation == "NS") %>%
fram %>%
  filter(Distance.To.Group < 6) %>%
ggplot( aes(Distance.To.Group,Transect.Meter.Mark, 
            color = interaction(transectOrientation, transectNumber_)))+
  geom_point(show.legend = FALSE) +
  facet_grid(transectNumber_ ~ transectOrientation)

fram %>%
  

```

